-- 1. Create the table
CREATE TABLE crop_sales_practice (
    sale_id SERIAL PRIMARY KEY,
    crop_name VARCHAR(50),
    sale_date DATE,
    quantity_kg INT,
    price_per_kg DECIMAL(10,2),
    total_revenue DECIMAL(10,2),
    region VARCHAR(50),
    status VARCHAR(20) -- 'Completed', 'Pending', 'Cancelled'
);

-- 2. Insert diverse test data
INSERT INTO crop_sales_practice (crop_name, sale_date, quantity_kg, price_per_kg, total_revenue, region, status) VALUES
('Paddy', '2026-04-01', 500, 22.00, 11000.00, 'North', 'Completed'),
('Cotton', '2026-04-05', 200, 60.00, 12000.00, 'South', 'Completed'),
('Paddy', '2026-04-10', 300, 23.00, 6900.00, 'North', 'Pending'),
('Maize', '2026-04-12', 1000, 18.50, 18500.00, 'West', 'Completed'),
('Cotton', '2026-04-15', 150, 62.00, 9300.00, 'North', 'Cancelled'),
('Maize', '2026-04-20', 400, 19.00, 7600.00, 'South', 'Completed'),
('Paddy', '2026-04-25', 600, 21.50, 12900.00, 'South', 'Completed'),
('Wheat', '2026-05-01', 800, 25.00, 20000.00, 'West', 'Completed');

-- Task 1 : -- Select all columns for sales that happened in the 'North' region.
select * from crop_sales_practice where region = 'North';

-- Task 2 : -- Select only crop_name and total_revenue for sales where the quantity is more than 500kg.
select crop_name,total_revenue from crop_sales_practice where (quantity_kg) > 500;

-- Task 3 : -- List all 'Completed' sales, ordered by total_revenue from highest to lowest.
select * from crop_sales_practice where status = 'Completed' order by  total_revenue desc;

-- Task 4 : -- Find all crops that start with the letter 'P'.
select * from crop_sales_practice where crop_name like 'P%';

-- Task 5 : -- Find all sales that happened in either the 'North' or 'South' regions (Use IN).
select * from crop_sales_practice where region in ('North', 'South');

-- Task 6 : -- Find all sales where the price_per_kg is between 20 and 30.
select * from crop_sales_practice where price_per_kg between 20 and 30;

-- Task 7 : -- Calculate the total revenue generated by each crop type.
select crop_name, SUM (total_revenue) as crop_revenue from crop_sales_practice group by crop_name;

-- Task 8 : -- Count how many sales were made in each region.
select region, count(*) as total_sales from crop_sales_practice group by region;

-- Task 9 : -- Show only the regions that have a total revenue greater than 20,000. (Requires GROUP BY and HAVING).
select region, sum(total_revenue) as total_region_revenue from crop_sales_practice group by region having  sum(total_revenue) >20000;

-- Task 10 : -- Create a query that shows crop_name and a new column called sale_size. If quantity_kg is > 500, label it 'Big Sale'; otherwise, label it 'Small Sale'. (Use CASE WHEN).
select crop_name, case when quantity_kg> 500 then 'Big Sale' else 'Small Sale' end as sale_size from crop_sales_practice; 
